### ISSUE TITLE
MemoryError when calling client.kin_account

### ISSUE THREAD

**Issue by hitwill** [kinecosystem/kin-sdk-python#70]
Same error happens when calling Keypair.address_from_seed and other similar functions.

Cause: [Reported](https://github.com/warner/python-ed25519/issues/12) as combination of Windows 10 development environment and Python version ^ 3.6.0

Resolution: Downgraded to python 3.6.0 and this solved the issue

**Comment by Ronserruya** [comment]
Thanks, we install this package since it works with windows, but I didnt know it has issues above 3.6. I will update here if we get a solution
