### ISSUE TITLE
How to subscribe to kin event stream?

### ISSUE THREAD

**Issue by ankitchiplunkar** [kinecosystem/kin-sdk-python#73]
I am trying to subscribe to all the confirmed stream of transactions happening on the kin blockchain. How can I subscribe to an event stream using kin's pythn sdk? 

If this is not an out of the box functionality, how can I use the horizon endpoints to create an event stream for myself?

**Comment by chancity** [comment]
Check out the info here https://www.stellar.org/developers/js-stellar-sdk/reference/examples.html#streaming-payment-events

and then for this SDK check here https://github.com/kinecosystem/kin-sdk-python/blob/2e2997f096c6ae9e017a31a56a8a7cc3ff9d1760/kin/sdk.py#L543

There are great examples of this being used here https://github.com/kinecosystem/payment-service/blob/master/payment/watcher.py

**Comment by ankitchiplunkar** [comment]
Thanks a lot :)

**Comment by Ronserruya** [comment]
We expose the functionality to stream txs for specific addresses, if you want to stream all txs, you can use this:

```python
import kin

client = kin.KinClient(kin.PROD_ENVIRONMENT)
stream = client.horizon.transactions(sse=True)
for event in stream:
    print(event)
```

This will print the events as they are received from the blockchain. If you want to parse them you can look at the code here and remove the filtering by address:
https://github.com/kinecosystem/kin-sdk-python/blob/v2-master/kin/monitors.py#L150

**Comment by ankitchiplunkar** [comment]
@chancity and @Ronserruya this is exactly what I was looking for thanks a lot :)

**Comment by ankitchiplunkar** [comment]
I made a barebones version of the twitter bot which tweets significant kin activity: https://github.com/ankitchiplunkar/kinexp/blob/master/tweet.py
