### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by sasharevzin** [kinecosystem/kin-sdk-python#74]
Hi guys,

I have a quick question. I'm a Ruby developer and I would like to know if there is a way to deploy a small app that can make payments?

I assume I can convert python SDK to ruby somehow?

Thanks.

**Comment by chancity** [comment]
@sasharevzin checkout this repository https://github.com/bloom-solutions/ruby-stellar-sdk.

When using the stellar SDK you need to change the network server and network id to send transactions.  I don't know how to change the server in the ruby stellar sdk but the two fields you need our below.  

Here is an example of how to send a payment using the sdk https://github.com/bloom-solutions/ruby-stellar-sdk/blob/master/examples/02_payment.rb

**Mainnet:**
network server: https://horizon.kinfederation.com/
network id: Kin Mainnet ; December 2018

**Testnet:** 
network server: https://horizon-testnet.kininfrastructure.com/
network id: Kin Testnet ; December 2018

Oh and the repo read me says this..
![image](https://user-images.githubusercontent.com/8220501/55370760-71b25280-54b0-11e9-9dbd-c15b3b0b951f.png)

**Comment by sasharevzin** [comment]
Wow, it was quick, thanks @chancity 😃
