### ISSUE TITLE
How to create a seed from public/private address

### ISSUE THREAD

**Issue by johnmrncc1701d** [kinecosystem/kin-sdk-python#84]
I have tried to create a keypair and seed in this way. I need the seed to get access to the account. I do not have the option to create a new seed with a new keypair. But I get an assert len(vk_s) == 32 error in ed25519.VerifyingKey. Can you help? ty

import kin
from kin_base.keypair import Keypair as BaseKeypair
import ed25519

public_address = ed25519.VerifyingKey(b"(public key of len 56)")
public_address = ed25519.SigningKey(b"(private key of len 56)")
kp = BaseKeypair(public_address, private_address)
seed = kp.seed()

**Comment by Ronserruya** [comment]
Hey, why are you trying to use these low-level methods?
You can use

```python
from kin import Keypair
kp = Keypair("private key of len 56") 
```

or like this if for some reason you need to base keypair object
from kin_base import Keypair
kp = Keypair.from_seed("private key of len 56") 
```

The ed25519 methods require keys of len 32, not 56. if this is what you have, you can use
```python
from kin_base import Keypair
kp = Keypair.from_raw_seed(b"private key of len 32")
```
